package com.soumya.expense_tracker_backend.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.soumya.expense_tracker_backend.dto.UserRegistrationRequest;
import com.soumya.expense_tracker_backend.dto.UserResponse;
import com.soumya.expense_tracker_backend.entity.User;
import com.soumya.expense_tracker_backend.util.NormalizationService;

@Mapper(componentModel = "spring", uses = NormalizationService.class) // Makes it a Spring bean
public interface UserMapper {

  // Request → Entity (ignore passwordHash – we'll set it manually)
  @Mapping(target = "passwordHash", ignore = true)
  @Mapping(target = "id", ignore = true) // Generated by DB
  @Mapping(target = "createdAt", ignore = true)
  @Mapping(target = "updatedAt", ignore = true)
  @Mapping(target = "accounts", ignore = true)
  @Mapping(target = "categories", ignore = true)
  @Mapping(target = "transactions", ignore = true)
  @Mapping(target = "username", source = "username", qualifiedByName = "normalize")
  @Mapping(target = "email", source = "email", qualifiedByName = "normalize")
  User toEntity(UserRegistrationRequest request);

  // Entity → Response (record)
  UserResponse toResponse(User user);

  // If you later add update request
  // @Mapping(target = ".", source = "request") // for partial updates if needed
}