package com.soumya.expense_tracker_backend.mapper;

import com.soumya.expense_tracker_backend.dto.UserRegistrationRequest;
import com.soumya.expense_tracker_backend.dto.UserResponse;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.soumya.expense_tracker_backend.entity.User;

@Mapper(componentModel = "spring") // Makes it a Spring bean
public interface UserMapper {

  // Request → Entity (ignore passwordHash – we'll set it manually)
  @Mapping(target = "passwordHash", ignore = true)
  @Mapping(target = "id", ignore = true) // Generated by DB
  @Mapping(target = "createdAt", ignore = true)
  @Mapping(target = "updatedAt", ignore = true)
  @Mapping(target = "accounts", ignore = true)
  User toEntity(UserRegistrationRequest request);

  // Entity → Response (record)
  UserResponse toResponse(User user);

  // If you later add update request
  // @Mapping(target = ".", source = "request") // for partial updates if needed
}